### ISSUE TITLE
The image value ranges from 0 to 1

### ISSUE THREAD

**Issue by Airliin** [kanydao/U-SAM#1]
Hello，Is the original image of the CARE dataset processed as 0-1？

**Comment by kanydao** [comment]
> Hello，Is the original image of the CARE dataset processed as 0-1？
Yes,for the convenience of model learning, we performed normalization operations on the images

**Comment by Airliin** [comment]
Thank you for your response. Is the normalization based on the maximum and minimum values of Hounsfield units (HU)? Were windowing operations such as abdominal window applied? If possible, could you provide me with the maximum and minimum values, as well as the normalization method? I would like to revert to the original values. Thank you.

**Comment by Airliin** [comment]
@kanydao Hello, I trained my own model using the CARE dataset. But the performance was poor when directly applying it to the WORD dataset, which has CT data with Hounsfield Unit values. How should I adjust the data distribution of the WORD dataset to fit the 0 to 1 range as in the CARE dataset? Thanks.

**Comment by kanydao** [comment]
@Airliin Thank you for your attention. We have expanded our previous work and added new clinical experiments. This project is still under continuous development and updates. Once our paper is accepted, we will provide the original data and more detailed tutorial guidance.
